In [1]:
import numpy as np

In [2]:
np.random.seed()

In [5]:
vector = np.random.randint(10, size=6) 
matrix = np.random.randint(10, size = (3,4)) 
tensor = np.random.randint(10, size = (3,4,5))

In [10]:
#number of dimensions
print( vector.ndim, matrix.ndim, tensor.ndim) 

1 2 3


In [11]:
#shape of the array
print( vector.shape, matrix.shape, tensor.shape)

(6,) (3, 4) (3, 4, 5)


In [12]:
#number of elements
print( vector.size, matrix.size, tensor.size)

6 12 60


In [13]:
#data type of tensors.
print( vector.dtype, matrix.dtype, tensor.dtype)

int32 int32 int32


In [25]:
#Index 0
print("V:", vector[0],"\nM:", matrix[0],"\nT:\n", tensor[0])

V: 2 
M: [5 1 3 3] 
T:
 [[0 8 6 0 2]
 [9 9 2 5 9]
 [0 0 0 4 0]
 [3 1 0 1 1]]


In [32]:
#first index on 1d, 2d, 3d
print("V:", vector[0],"\nM:", matrix[0][0],"\nT:", tensor[0][0], "\nT:", tensor[0][0][0])

V: 2 
M: 5 
T: [0 8 6 0 2] 
T: 0


In [34]:
vector

array([2, 5, 6, 7, 7, 2])

In [35]:
vector[:3]

array([2, 5, 6])

In [36]:
vector[3:]

array([7, 7, 2])

In [37]:
vector[::2]

array([2, 6, 7])

In [38]:
matrix

array([[5, 1, 3, 3],
       [7, 3, 9, 3],
       [1, 6, 6, 9]])

In [43]:
matrix[:,::2]

array([[5, 3],
       [7, 9],
       [1, 6]])

In [44]:
matrix[:,:3]

array([[5, 1, 3],
       [7, 3, 9],
       [1, 6, 6]])

In [45]:
vector[1] = 99
vector

array([ 2, 99,  6,  7,  7,  2])

In [52]:
matrix[:,0] = np.zeros(1)

In [53]:
matrix

array([[0, 1, 3, 3],
       [0, 3, 9, 3],
       [0, 6, 6, 9]])

In [57]:
np.zeros(3)

array([0., 0., 0.])

In [58]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
# pointing to the same Memory Location
fake_copy = vector
print(id(vector)) 
print(id(fake_copy)) 


2000075742736
2000075742736


In [61]:
# .copy() is necessary
real_copy = vector.copy() 
print(id(vector)) 
print(id(real_copy)) 

2000075742736
2000092599856


In [63]:
print(vector)
print(real_copy) 
print(fake_copy)

[ 2 99  6  7  7  2]
[ 2 99  6  7  7  2]
[ 2 99  6  7  7  2]


In [64]:
# Demonstration
vector[0] = 0 
print(vector)
print(real_copy) 
print(fake_copy)

[ 0 99  6  7  7  2]
[ 2 99  6  7  7  2]
[ 0 99  6  7  7  2]


In [65]:
x1 = np.array([1,2,3]) 
x2 = np.array([4,5,6])
np.concatenate([x1,x2]) 

array([1, 2, 3, 4, 5, 6])

In [67]:
matrix = np.array([[1,2,3],
                   [4,5,6]])


In [68]:
np.concatenate([matrix,matrix])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
np.concatenate([matrix,matrix], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [70]:
x = np.array([1,2,3]) 
grid = np.array([[4,5,6],
                  [7,8,9]])

In [71]:
np.vstack([x,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
x = np.array( [ [99],  [99] ] )

In [77]:
np.hstack([x,grid])

array([[99,  4,  5,  6],
       [99,  7,  8,  9]])

In [78]:
x = np.array([1,2,3,4,5,6,7,8,9,10])

In [100]:
first, sec = np.split(x, [8])

In [101]:
print(first, sec)

[1 2 3 4 5 6 7 8] [ 9 10]


In [98]:
matrix = np.arange(16).reshape((4,4))

In [99]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [123]:
# vsplit taking the row  index as  argument
upper, lower = np.vsplit(matrix, [3]) 
print(upper,"\n --- \n", lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 --- 
 [[12 13 14 15]]


In [126]:
# hsplit taking the column  index as  argument
left, right = np.hsplit(matrix, [2]) 
print(left,"\n --- \n ", right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
 --- 
  [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [127]:
def compute_inverse(values):
    out = np.empty(len(values))
    for i in range (len(values)):
        out[i] = 1.0 / values[i] 
    return out 

In [138]:
# Comparing the efficiency
values = np.random.randint(1, 100, size = 10000000 ) 

In [139]:
%%timeit -n 1 -r 1
compute_inverse(values)

16.1 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [141]:
%%timeit -n 1 -r 1
print(1.0/values)

[0.04       0.01086957 0.01515152 ... 0.01219512 0.01428571 0.01282051]
37.8 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [143]:
x = np.arange(10)

In [144]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
print(x+2)   

print(np.add(x,2))

[ 2  3  4  5  6  7  8  9 10 11]
[ 2  3  4  5  6  7  8  9 10 11]


In [156]:
print(x-2) 

print(np.subtract(x,2))

[-2 -1  0  1  2  3  4  5  6  7]
[-2 -1  0  1  2  3  4  5  6  7]


In [157]:
print(x*3) 

print(np.multiply(x,3))

[ 0  3  6  9 12 15 18 21 24 27]
[ 0  3  6  9 12 15 18 21 24 27]


In [158]:
print(x/4) 

print(np.divide(x,4))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25]


In [161]:
print(x//4) 

print(np.floor_divide(x,4))

[0 0 0 0 1 1 1 1 2 2]
[0 0 0 0 1 1 1 1 2 2]


In [162]:
print(x**2) 

print( np.power(x, 2) )

[ 0  1  4  9 16 25 36 49 64 81]
[ 0  1  4  9 16 25 36 49 64 81]


In [163]:
print(x%3) 

print( np.mod(x, 3) )

[0 1 2 0 1 2 0 1 2 0]
[0 1 2 0 1 2 0 1 2 0]


In [165]:
x = np.array([-2,-1,0,1,2])

In [166]:
print(abs(x)) 
print(np.absolute(x))
print(np.abs(x))

[2 1 0 1 2]
[2 1 0 1 2]
[2 1 0 1 2]


In [167]:
x = np.random.random(100)

In [169]:
np.sum(x)

51.196619177806255

In [170]:
np.min(x)

0.01649741437592256

In [171]:
np.max(x)

0.9872746269018668

In [172]:
np.mean(x)

0.5119661917780626

In [174]:
np.median(x)

0.5150671090942409

In [175]:
x = np.random.random ((5,2))

In [182]:
x

array([[0.09373028, 0.22135517],
       [0.79336862, 0.79368666],
       [0.71836454, 0.42587705],
       [0.06404789, 0.45391639],
       [0.02173236, 0.23287817]])

In [183]:
x.min(axis = 1) 


array([0.09373028, 0.79336862, 0.42587705, 0.06404789, 0.02173236])

In [184]:
x.min(axis = 0)

array([0.02173236, 0.22135517])

In [185]:
a = np.array([1,2,3])
b = np.array([4,5,6]) 
np.dot(a,b)

32

In [187]:
a = np.array([1,2,3]) 
matrix = np.array([[1,2,3],
                  [4,5,6]]) 
np.dot(matrix,a)

array([14, 32])